### ISSUE TITLE
ImportError from urllib3: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by cnmeeia** [kxxt/aspeak#28]
```sh
/Users/meeia ~ aspeak -t "Hello, world"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/aspeak", line 5, in <module>
    from aspeak.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aspeak/__main__.py", line 1, in <module>
    from .cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aspeak/cli/__init__.py", line 1, in <module>
    from .main import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aspeak/cli/main.py", line 8, in <module>
    from .voices import list_voices
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aspeak/cli/voices.py", line 1, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
/Users/meeia ~

```

**Comment by cnmeeia** [comment]
```sh
/Users/meeia ~ aspeak -t "Hello, world"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/aspeak", line 5, in <module>
    from aspeak.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aspeak/__main__.py", line 1, in <module>
    from .cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aspeak/cli/__init__.py", line 1, in <module>
    from .main import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aspeak/cli/main.py", line 8, in <module>
    from .voices import list_voices
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aspeak/cli/voices.py", line 1, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
/Users/meeia ~

```

```shell
[root@amd ~]#  aspeak -t "Hello, world"
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/python3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/python3/lib/python3.10/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/bin/aspeak", line 5, in <module>
    from aspeak.__main__ import main
  File "/usr/local/python3/lib/python3.10/site-packages/aspeak/__init__.py", line 7, in <module>
    from azure.cognitiveservices.speech import SpeechSynthesisOutputFormat, \
  File "/usr/local/python3/lib/python3.10/site-packages/azure/cognitiveservices/speech/__init__.py", line 8, in <module>
    from .speech import *
  File "/usr/local/python3/lib/python3.10/site-packages/azure/cognitiveservices/speech/speech.py", line 11, in <module>
    from . import audio
  File "/usr/local/python3/lib/python3.10/site-packages/azure/cognitiveservices/speech/audio.py", line 9, in <module>
    from . import speech_py_impl as impl
  File "/usr/local/python3/lib/python3.10/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 17, in <module>
    _speech_py_impl = swig_import_helper()
  File "/usr/local/python3/lib/python3.10/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 16, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
  File "/usr/local/python3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_speech_py_impl'
```

**Comment by kxxt** [comment]
升级 `urllib3`: `pip install --upgrade urllib3`

**Comment by kxxt** [comment]
> ```
> ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/python3/lib/python3.10/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so)
> ```

这个问题是你的系统的 C++ 标准库版本过低导致的，你需要升级 libstdc++  到一个支持 CXXABI_1.3.8 的 版本
