### ISSUE TITLE
error

### ISSUE THREAD

**Issue by selfdisciplineman** [kxxt/aspeak#46]
Traceback (most recent call last):
  File "/opt/homebrew/bin/aspeak", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/aspeak/cli/main.py", line 138, in main
    speech = create_speech(args.locale, args.voice, audio_format)
  File "/opt/homebrew/lib/python3.9/site-packages/aspeak/api/api.py", line 138, in __init__
    super().__init__(locale, voice, audio_format, output)
  File "/opt/homebrew/lib/python3.9/site-packages/aspeak/api/api.py", line 43, in __init__
    self._config()
  File "/opt/homebrew/lib/python3.9/site-packages/aspeak/api/api.py", line 51, in _config
    assert token is not None
AssertionError

**Comment by cj-neo** [comment]
我也遇到同樣的問題，直接發音可以，但是無法輸出到音樂檔

例如：

aspeak -t "你好，世界！" -l zh-CN -o test.wav

這樣就會出現同樣的錯誤了

**Comment by kxxt** [comment]
Sometimes it is just a result of poor internet connection. v3 still works for me. 

I have just released v4, which is a rust-rewritten version of aspeak.
